# Generated by Django 3.2.5 on 2022-01-29 12:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0003_auto_20220129_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
