# Generated by Django 3.2.5 on 2022-03-18 15:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0005_auto_20220318_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/teams/')),
                ('prayer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('total_goals', models.IntegerField(blank=True, null=True)),
                ('total_assists', models.IntegerField(blank=True, null=True)),
                ('total_yellow', models.IntegerField(blank=True, null=True)),
                ('total_red', models.IntegerField(blank=True, null=True)),
                ('goal_summary', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('assists_summary', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('yellow_summary', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('red_summary', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('all_summary', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
    ]
