# Generated by Django 3.2.5 on 2022-03-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0006_teaminformations'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='u',
            field=models.URLField(blank=True, null=True),
        ),
    ]
