# Generated by Django 3.2.5 on 2022-03-20 07:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0008_teaminformations_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msimamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('msimamo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('mod_date', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
