# Generated by Django 3.2.5 on 2022-03-20 11:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0010_ratiba_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msimamo',
            old_name='mod_date',
            new_name='playing_date',
        ),
        migrations.RenameField(
            model_name='ratiba',
            old_name='mod_date',
            new_name='playing_date',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='matokeo',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='mod_date',
            new_name='playing_date',
        ),
        migrations.AddField(
            model_name='ratiba',
            name='header',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='ratiba',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
