# Generated by Django 3.2.5 on 2022-03-20 13:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0011_auto_20220320_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='msimamo',
            name='header',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
