# Generated by Django 3.2.5 on 2022-03-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0015_auto_20220324_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratiba',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
